### ISSUE TITLE
Server Error, Attacks of one player don't work

### ISSUE THREAD

**Issue by BreabCat** [cleannrooster/spellblades-1.20.1#15]
Minecraft version: 1.20.1
Mod version: 1.5.2
Loader version: 1.15.7

On our modded server, one specific player can no longer hit anything after using the hexblade offering. Every other player has no issues, just this one and just after using the offering. When they try to hit a mob the console throws the following error:

[00:43:41] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1324.method_6194()" because "addedinstance1" is null
        at net.minecraft.class_5131.handler$ehn000$spellbladenext$getAttributeValueSpellblades(class_5131.java:1055) ~[server-intermediary.jar:?]
        at net.minecraft.class_5131.method_26852(class_5131.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_7324(class_1657.java:1195) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_7324(class_3222.java:1491) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244$1.method_34218(class_3244.java:1610) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824$1.method_34213(class_2824.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1571) ~[server-intermediary.jar:?]
        at net.bettercombat.network.ServerNetwork.lambda$initializeHandlers$5(ServerNetwork.java:199) ~[bettercombat-fabric-1.8.4+1.20.1.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by cleannrooster** [comment]
There's a few things you can do, you can have the player switch dimensions
such as to the nether, die, or reset the player file, from least to most
invasive. If you wish, you can try to fix by updating to the newest version
but I see that you're quite behind so updating all the mods might be
difficult.

**Comment by cleannrooster** [comment]
Try restarting the server too if you haven't already

**Comment by BreabCat** [comment]
Thanks, I pulled the player data from a backup we still had and replaced it. That fixed it. Thanks for the help!

**Comment by BreabCat** [comment]
It might've been the Ashes of the Stars Item causing it as they made that just yesterday and the error kept coming up until they took it off
